name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 700 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@98.81.238.194 -t "cd ~/test-app-devops &&
            git pull origin main &&
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash && source ~/.bashrc &&
            nvm install --lts &&
            npm i -g pnpm && npm i -g pm2 &&
            pnpm install &&
            pnpm build &&

            pm2 restart all || pm2 start pnpm --name http-server -- run dev"
            "