name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 700 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@98.81.238.194 << 'EOF'
            cd ~/test-app-devops
            git pull origin main

            pnpm install
            pnpm build

            pm2 restart all
          EOF