name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          chmod 600 ssh_key

          ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@54.91.77.197 "bash -c '
            # install node if missing
            command -v node || (
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&
              sudo apt install -y nodejs
            )

            # install pnpm & pm2 WITH sudo (fixes EACCES)
            command -v pnpm || sudo npm install -g pnpm
            command -v pm2 || sudo npm install -g pm2

            cd ~/test-app-devops &&
            git pull origin main &&

            pnpm install &&
            pnpm build &&

            pm2 restart all || pm2 start pnpm --name http-server -- run dev
          '"